AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  bucket:
    Type: String

Resources:
  CodeDeployEC2ServiceRole:      
    Type: AWS::IAM::Role
    Properties:
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
          - "arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy"
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "ec2.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        RoleName: "CodeDeployEC2ServiceRole" 
  CodeDeployServiceRole:      
    Type: AWS::IAM::Role
    Properties: 
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
          - "arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy"
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "codedeploy.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        RoleName: "CodeDeployServiceRole"

  LambdaRole:      
      Type: AWS::IAM::Role
      Properties: 
          ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
            - "arn:aws:iam::aws:policy/AmazonSESFullAccess"
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole"
          AssumeRolePolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Principal: 
                  Service: 
                    - "lambda.amazonaws.com"
                Action: 
                  - "sts:AssumeRole"
          Path: "/"
          RoleName: "LambdaRole" 

  AWSServiceRoleForAutoScaling:      
      Type: AWS::IAM::ServiceLinkedRole
      Properties: 
        AWSServiceName: "autoscaling.amazonaws.com"
        ## Role


  Policy1:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
        ManagedPolicyName: "circleci-ec2-ami"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action: 
                - "ec2:AttachVolume"
                - "ec2:AuthorizeSecurityGroupIngress"
                - "ec2:CopyImage"
                - "ec2:CreateImage"
                - "ec2:CreateKeypair"
                - "ec2:CreateSecurityGroup"
                - "ec2:CreateSnapshot"
                - "ec2:CreateTags"
                - "ec2:CreateVolume"
                - "ec2:DeleteKeyPair"
                - "ec2:DeleteSecurityGroup"
                - "ec2:DeleteSnapshot"
                - "ec2:DeleteVolume"
                - "ec2:DeregisterImage"
                - "ec2:DescribeImageAttribute"
                - "ec2:DescribeImages"
                - "ec2:DescribeInstances"
                - "ec2:DescribeInstanceStatus"
                - "ec2:DescribeRegions"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeSnapshots"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeTags"
                - "ec2:DescribeVolumes"
                - "ec2:DetachVolume"
                - "ec2:GetPasswordData"
                - "ec2:ModifyImageAttribute"
                - "ec2:ModifyInstanceAttribute"
                - "ec2:ModifySnapshotAttribute"
                - "ec2:RegisterImage"
                - "ec2:RunInstances"
                - "ec2:StopInstances"
                - "ec2:TerminateInstances"
              Resource: "*"
        Users:
          - "circleci"
  Policy2:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
        ManagedPolicyName: "CodeDeploy-EC2-S3"

        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -

              Effect: "Allow"
              Action:
               - "s3:*"
              Resource: "*"
        Roles:
          - !Ref "CodeDeployEC2ServiceRole"
  Policy3:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
        ManagedPolicyName: "CircleCI-Upload-To-S3"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action: 

                - "s3:*"
              Resource: 
                - !Sub "arn:aws:s3:::${bucket}"
                - !Sub "arn:aws:s3:::${bucket}/*"

        Users:
          - "circleci"
  Policy4:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
        ManagedPolicyName: "CirlceCI-Code-Deploy"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action:
                - "codedeploy:RegisterApplicationRevision"
                - "codedeploy:GetApplicationRevision"
              Resource: !Join 
                          - ":"
                          - - "arn:aws:codedeploy"
                            - !Ref AWS::Region
                            - !Ref AWS::AccountId

                            - "application:csye6225-webapp"          

            -
              Effect: "Allow"
              Action: 
                - "codedeploy:CreateDeployment"
                - "codedeploy:GetDeployment"
              Resource: "*"  
            -
              Effect: "Allow"
              Action: 
                - "codedeploy:GetDeploymentConfig"
              Resource: 
                - !Join 
                    - ":"
                    - - "arn:aws:codedeploy"
                      - !Ref AWS::Region
                      - !Ref AWS::AccountId 
                      - "deploymentconfig:CodeDeployDefault.OneAtATime"
                - !Join 
                    - ":"
                    - - "arn:aws:codedeploy"
                      - !Ref AWS::Region
                      - !Ref AWS::AccountId
                      - "deploymentconfig:CodeDeployDefault.HalfAtATime"
                - !Join 
                    - ":"
                    - - "arn:aws:codedeploy"
                      - !Ref AWS::Region
                      - !Ref AWS::AccountId
                      - "deploymentconfig:CodeDeployDefault.AllAtOnce"
        Users:
          - "circleci"
  AWSLambda:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
        ManagedPolicyName: "AWSLambda"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Action:
                - "cloudformation:DescribeChangeSet"
                - "cloudformation:DescribeStackResources"
                - "cloudformation:DescribeStacks"
                - "cloudformation:GetTemplate"
                - "cloudformation:ListStackResources"
                - "cloudwatch:*"
                - "cognito-identity:ListIdentityPools"
                - "cognito-sync:GetCognitoEvents"
                - "cognito-sync:SetCognitoEvents"
                - "dynamodb:*"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeVpcs"
                - "events:*"
                - "iam:GetPolicy"
                - "iam:GetPolicyVersion"
                - "iam:GetRole"
                - "iam:GetRolePolicy"
                - "iam:ListAttachedRolePolicies"
                - "iam:ListRolePolicies"
                - "iam:ListRoles"
                - "iam:PassRole"
                - "iot:AttachPrincipalPolicy"
                - "iot:AttachThingPrincipal"
                - "iot:CreateKeysAndCertificate"
                - "iot:CreatePolicy"
                - "iot:CreateThing"
                - "iot:CreateTopicRule"
                - "iot:DescribeEndpoint"
                - "iot:GetTopicRule"
                - "iot:ListPolicies"
                - "iot:ListThings"
                - "iot:ListTopicRules"
                - "iot:ReplaceTopicRule"
                - "kinesis:DescribeStream"
                - "kinesis:ListStreams"
                - "kinesis:PutRecord"
                - "kms:ListAliases"
                - "lambda:*"
                - "logs:*"
                - "s3:*"
                - "sns:ListSubscriptions"
                - "sns:ListSubscriptionsByTopic"
                - "sns:ListTopics"
                - "sns:Publish"
                - "sns:Subscribe"
                - "sns:Unsubscribe"
                - "sqs:ListQueues"
                - "sqs:SendMessage"
                - "tag:GetResources"
                - "xray:PutTelemetryRecords"
                - "xray:PutTraceSegments"
              Resource: "*"
        Users:
          - "circleci"

  EC2InstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          !Ref "CodeDeployEC2ServiceRole"
      InstanceProfileName: "CodeDeployEC2ServiceRole"
  CodeDeployInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          !Ref "CodeDeployServiceRole"

      InstanceProfileName: "CodeDeployServiceRole"
      ## CodeDeploy
  LambdaFunctionInsProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          !Ref "LambdaRole"

      InstanceProfileName: "LambdaRole"

Outputs:
  EC2InstanceProfile: 
    Description: Codeploy Role for Ec2 Instance
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-Ec2InstanceProfile
  CodeDeployEC2ServiceRole: 
    Description: Codeploy Role 
    Value: !GetAtt CodeDeployServiceRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CodeDeployServiceRole-Arn
